safe: true
title: 'Brad Dunbar'
author: 'Brad Dunbar'
description: 'Programming & Peanut Butter'
url: 'https://braddunbar.net'
permalink: '/:year/:month/:day/:title'
markdown: 'kramdown'
sass:
  style: compressed
